(() => {
"use strict";
const D=window.DEMO_DATA;
const $=s=>document.querySelector(s);
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
const a=(text,href)=>{const n=el("a",text);n.href=href;return n};
const sections=[["command","Command Center","◈"],["signals","Signals","⌁"],["analyst","Analyst","✧"],["competitors","Competitors","▦"],["reports","Reports","▤"],["developer","Developer","⌘"]];
const C=id=>D.competitors.find(c=>c.id===Number(id));
const root=$("#app");
const side=el("aside"),brand=el("div",undefined,"brand");
brand.append(el("b","ci"),document.createTextNode("Intelligence"),el("small","COMPETITIVE INTELLIGENCE"));
const nav=el("nav");nav.setAttribute("aria-label","Main navigation");
sections.forEach(([id,name,icon])=>{const l=a("", "#"+id);l.dataset.page=id;l.append(el("span",icon),document.createTextNode(name));nav.append(l)});
const bottom=el("div",undefined,"side-bottom");bottom.append(el("span",undefined,"online"),document.createTextNode("Local design environment"),el("p","Same data. Four visual directions."));
side.append(brand,nav,bottom);
const main=el("main"),top=el("div",undefined,"topline"),trail=el("span","Workspace / Overview");
top.append(trail,el("span",document.body.dataset.design+" · STATIC DESIGN DEMO","demo-label"));
const head=el("header"),heading=el("div"),kicker=el("div","YOUR INTELLIGENCE WORKSPACE","eyebrow"),h1=el("h1"),sub=el("p",undefined,"muted");heading.append(kicker,h1,sub);
const ask=a("Ask Analyst ↗","#analyst");ask.className="button primary";head.append(heading,ask);
const content=el("div");main.append(top,head,content,el("div","DESIGN FIXTURES ONLY · Not live intelligence · No API requests, database writes or real analysis tasks.","footer"));root.append(side,main);
function button(text,fn){const b=el("button",text);b.addEventListener("click",fn);return b}
function section(title,body,href){const s=el("section",undefined,"section"),bar=el("div",undefined,"section-head");bar.append(el("h2",title));if(href)bar.append(a("View all →",href));s.append(bar,body);return s}
function grid(items,render){const g=el("div",undefined,"grid");if(!items.length)g.append(el("div","No verified facts available yet.","empty"));else items.forEach(x=>g.append(render(x)));return g}
function signal(s){const c=C(s.cid),card=el("article",undefined,"card signal"),body=el("div"),tags=el("div");tags.append(el("span",s.category,"tag"),el("span",s.type,"tag"+(s.type==="UNCOMPARABLE"?" warn":"")));body.append(tags,el("h3",s.title),el("small",c.name));
const change=el("div",undefined,"change");if(s.old)change.append(el("del",s.old),el("span","→","arrow"));change.append(el("span",s.value));body.append(change);
const evidence=el("details");evidence.append(el("summary","View evidence & source"),el("blockquote",s.evidence),el("p","Source reference: https://"+c.domain+s.path),el("small","Synthetic design evidence — not a verified live claim."));body.append(evidence);
const actions=el("div",undefined,"actions");actions.append(a("Competitor profile","#competitors/"+c.id),a("Developer details","#developer"));body.append(actions);card.append(el("div",c.initial,"monogram"),body,el("time",s.date,"stamp"));return card}
function competitor(c){const n=el("article",undefined,"card"),bar=el("div",undefined,"card-top");bar.append(el("div",c.initial,"monogram"),el("span",c.status,"status"));n.append(bar,el("h3",c.name),el("small",c.domain),el("p",c.description,"muted"));const foot=el("div",undefined,"card-foot");foot.append(el("span",c.sources+" verified sources"),el("span",D.signals.filter(s=>s.cid===c.id).length+" signals"));n.append(foot);const actions=el("div",undefined,"actions");actions.append(a("Open intelligence profile →","#competitors/"+c.id));n.append(actions);return n}
function home(){const metrics=el("div",undefined,"metrics");[["Tracked competitors","03","Official sources connected"],["Signals · last 30 days","06","Across your workspace"],["Last successful check","09:42","September 21, 2026"],["Needs attention","01","Source review required"]].forEach(([label,value,note])=>{const m=el("div",undefined,"metric");m.append(el("small",label),el("strong",value),el("em",note));metrics.append(m)});content.append(metrics);
const attention=el("div",undefined,"card attention");attention.append(el("div","L","monogram"));const t=el("div");t.append(el("span","REVIEW REQUIRED","tag warn"),el("h3","Linear · Facts need verification"),el("p","Official pages collected. Real fact extraction is not connected in this preview."));const actions=el("div",undefined,"actions");actions.append(a("Review competitor →","#competitors/2"));attention.append(t,actions);
content.append(section("Needs Attention",attention));const feed=el("div");D.signals.slice(0,3).forEach(s=>feed.append(signal(s)));content.append(section("Recent Signals",feed,"#signals"),section("Competitor overview",grid(D.competitors,competitor),"#competitors"))}
function signals(){const filters=el("form",undefined,"filters"),list=el("div");function select(label,values){const l=el("label",label),s=el("select");values.forEach(([v,t])=>{const o=el("option",t);o.value=v;s.append(o)});l.append(s);filters.append(l);return s}
const who=select("Competitor",[["","All competitors"],...D.competitors.map(c=>[c.id,c.name])]);const type=select("Signal type",[["","All types"],...["Pricing","Feature","Product","Source","Positioning"].map(x=>[x,x])]);const change=select("Change",[["","All changes"],...["ADDED","MODIFIED","REMOVED","UNCOMPARABLE"].map(x=>[x,x])]);const status=select("Status",[["","All statuses"],["review","Needs review"],["confirmed","Confirmed"]]);const dateLabel=el("label","From"),date=el("input");date.type="date";dateLabel.append(date);filters.append(dateLabel);
function draw(){const result=D.signals.filter(s=>(!who.value||s.cid===Number(who.value))&&(!type.value||s.category===type.value)&&(!change.value||s.type===change.value)&&(!date.value||s.date>=date.value)&&(!status.value||(s.type==="UNCOMPARABLE")===(status.value==="review")));list.replaceChildren(...result.map(signal));if(!result.length)list.append(el("p","No matching signals.","empty"))}
filters.addEventListener("change",draw);filters.addEventListener("submit",e=>e.preventDefault());content.append(filters,list);draw()}
function report(r){const n=el("article",undefined,"card report-line"),body=el("div");body.append(el("span",r.type,"tag"),el("h3",r.title),el("small",r.date+" · "+r.changes+" recorded changes · "+(r.cid===2?"Completed with warnings":"Completed")));const acts=el("div",undefined,"actions");acts.append(a("View report","#reports/"+r.id),button("Markdown ↓",()=>{const blob=new Blob([reportText(r)],{type:"text/markdown"}),url=URL.createObjectURL(blob),link=a("",url);link.download="demo-report-"+r.id+".md";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}));n.append(body,acts);return n}
function reportText(r){return "# "+r.title+"\n\nDESIGN DEMO — synthetic data, not live intelligence.\n\n"+D.signals.filter(s=>s.cid===r.cid).map(s=>"## "+s.title+"\n"+s.value+"\nEvidence: "+s.evidence).join("\n\n")}
function profile(id){const c=C(id);if(!c){content.append(el("p","Competitor not found.","empty"));return}h1.textContent=c.name;sub.textContent=c.domain+" · "+c.status+" · Last checked "+c.checked;const tabs=el("div",undefined,"tabs"),body=el("div");content.append(tabs,body);function show(name){tabs.querySelectorAll("button").forEach(b=>b.classList.toggle("active",b.textContent===name));body.replaceChildren();const feed=()=>{const f=el("div");D.signals.filter(s=>s.cid===c.id).forEach(s=>f.append(signal(s)));return f};const facts=()=>grid(c.facts,x=>{const n=el("article",undefined,"card");n.append(el("span","FEATURE","tag"),el("h3",x),el("small","Demo evidence · official product page"));return n});
if(name==="Overview"){body.append(el("p",c.description,"notice"),section("Current facts",facts()),section("Recent changes",feed()))}
if(name==="Signals"||name==="History")body.append(feed());
if(name==="Pricing"){body.append(el("div",c.price||"No verified facts available yet.","card"));D.signals.filter(s=>s.cid===c.id&&s.category==="Pricing").forEach(s=>body.append(signal(s)))}
if(name==="Features")body.append(facts());
if(name==="Sources"){body.append(grid(["Homepage","Features","Pricing","Changelog"].slice(0,c.sources),x=>{const n=el("article",undefined,"card");n.append(el("span","VERIFIED · DEMO","tag"),el("h3",x),el("p",c.domain),el("small","Latest snapshot: SUCCESS · "+c.checked));return n}))}
if(name==="Reports")D.reports.filter(r=>r.cid===c.id).forEach(r=>body.append(report(r)));
}
["Overview","Signals","Pricing","Features","Sources","History","Reports"].forEach(name=>tabs.append(button(name,()=>show(name))));show("Overview")}
function analyst(){const chat=el("div",undefined,"chat"),log=el("div",undefined,"chat-log"),form=el("form",undefined,"composer"),input=el("input");input.placeholder="查看 Notion 最近变化";input.required=true;input.setAttribute("aria-label","Analyst command");const send=el("button","Send");send.type="submit";send.className="primary";form.append(input,send);
chat.append(el("div","Analyst Preview · Deterministic demo queries only. Real AgentProvider and fact extraction are not connected. No real task will be started.","notice"));const examples=el("div",undefined,"suggestions");["最近有哪些变化","查看 Notion 当前价格","为什么本次没有提取事实"].forEach(x=>examples.append(button(x,()=>{input.value=x;input.focus()})));chat.append(examples,log,form);content.append(chat);
form.addEventListener("submit",e=>{e.preventDefault();const q=input.value.trim();input.value="";log.append(el("div",q,"bubble user"));const reply=el("div",undefined,"bubble");log.append(reply);const c=D.competitors.find(c=>q.toLowerCase().includes(c.name.toLowerCase()));
if(q==="最近有哪些变化"||q==="查看最近 signals"||/最近变化$/.test(q)){D.signals.filter(s=>!c||s.cid===c.id).slice(0,3).forEach(s=>reply.append(signal(s)));return}
if(q==="为什么本次没有提取事实"){reply.textContent="真实事实提取尚未接入。此 Demo 只展示固定设计数据，不抓取页面或提取事实。";return}
if(/^打开运行\s+\d+$/.test(q)){reply.append(a("Open developer trace →","#developer"));return}
if(/^(分析|重新分析)\s+/.test(q)){reply.textContent="视觉预览：已识别分析命令。Demo 不会启动真实 Agent 任务或写入数据库。";return}
if(c&&/最新报告$/.test(q)){reply.append(report(D.reports.find(r=>r.cid===c.id)));return}
if(c&&/当前价格$/.test(q)){reply.textContent=c.price||"No verified facts available yet.";return}
if(c&&/来源$/.test(q)){reply.append(a(c.domain+" · "+c.sources+" sources","#competitors/"+c.id));return}
reply.textContent="Natural-language Analyst is not connected yet.";
})}
function developer(){const layout=el("div",undefined,"trace"),runs=el("div",undefined,"card"),result=el("div",undefined,"card"),audit=el("div",undefined,"card");runs.append(el("h2","Runs"));layout.append(runs,result,audit);content.append(el("div","Developer / Audit mode · All runs below are fixed design fixtures.","notice"),section("Execution workspace",layout));
function show(r){runs.querySelectorAll("button").forEach(b=>b.classList.toggle("active",b.dataset.id===String(r.id)));result.replaceChildren(el("span",r.status,"tag"),el("h2",C(r.cid).name+" analysis"),el("p",r.provider+" · "+r.tools+" tool calls","muted"),el("p","Read profile → collect pages → check evidence → prepare report.","notice"));D.signals.filter(s=>s.cid===r.cid).forEach(s=>result.append(signal(s)));audit.replaceChildren(el("h2","Execution trace"));["Profile lookup","Source validation","Page fetching","Evidence checking","Report generation"].forEach((name,i)=>{const d=el("details",undefined,"event");d.append(el("summary",name+" · SUCCEEDED"),el("p","Attempt 1 · "+(i+1)*120+" ms"),el("p","Sanitized demo audit payload. No credentials or raw HTML."));audit.append(d)});if(r.cid===2)audit.append(el("p","Fact extraction: SKIPPED","notice"))}
D.runs.forEach(r=>{const b=button(C(r.cid).name+" · #"+r.id,()=>show(r));b.className="run";b.dataset.id=r.id;runs.append(b)});show(D.runs[0])}
function render(){const [page,id]=(location.hash.slice(1)||"command").split("/"),found=sections.find(s=>s[0]===page)||sections[0];nav.querySelectorAll("a").forEach(n=>n.classList.toggle("active",n.dataset.page===found[0]));trail.textContent="Workspace / "+found[1];h1.textContent=found[1]==="Command Center"?"Your competitive landscape":found[1];sub.textContent=({command:"Changes worth your attention. Evidence behind every signal.",signals:"A clear record of what changed, when, and where.",analyst:"Explore your intelligence with controlled workspace queries.",competitors:"The products you track. The context you need.",reports:"Evidence-backed briefings, ready to review.",developer:"Inspect the process behind every result."})[found[0]];document.title=document.body.dataset.design+" — "+found[1];content.replaceChildren();({command:home,signals,analyst,competitors:()=>id?profile(id):content.append(grid(D.competitors,competitor)),reports:()=>{const r=D.reports.find(r=>r.id===Number(id));if(r){content.append(report(r),el("pre",reportText(r),"card report-view"))}else D.reports.forEach(r=>content.append(report(r)))},developer})[found[0]]();window.scrollTo(0,0)}
window.addEventListener("hashchange",render);render();
})();
